config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'add_activity', to: 'static_pages#add_activity', as: 'add_activity'
  resources :users
  resources :activities
  resources :activities do
    collection do
      get :weekly_distances
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  
  default_scope -> {order(run_at: :desc)}
  validates :user_id, presence: true
  validates :distance, presence: true, numericality: {greater_than: 0}
  validates :hours, numericality: { greater_than_or_equal_to: 0 }
  validates :minutes, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 60 }
  validates :seconds, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 60 }, presence: true
  validates :run_at, presence: true
  validates :description, length: { maximum: 140 }

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
    before_action :correct_user, only: [:edit, :update, :destroy]
    
    def new
        @activity = Activity.new
    end

    def create
        @activity = current_user.activities.build(activity_params)
        if @activity.save
            flash[:success] = "Activity created"
            redirect_to root_url
        else
            render 'new'
        end
    end

    def edit
        @activity = Activity.find_by(id: params[:id])
    end

    def update
        @activity = Activity.find_by(id: params[:id])
        if @activity.update(activity_params)
            flash[:success] = "Activity updated"
            redirect_to root_path
        else
            render 'edit'
        end
    end

    def destroy
        @activity.destroy
        flash[:success] = "Activity deleted"
        redirect_to request.referrer || root_url
    end

    private
        def activity_params
            params.require(:activity).permit(:distance, :hours, :minutes, :seconds, :title, :description, :run_at, :location)
        end
        
        def correct_user
            @activity = Activity.find_by(id: params[:id])
            redirect_to root_url unless @activity && (current_user.admin? || @activity.user == current_user)
        end
        
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<li id="activity-<%= activity.id %>" class="activity-card mb-4">
  <div class="activity-card-body">
    <div class="d-flex align-items-center mb-3">
      <%= link_to gravatar_for(activity.user, size: 50), activity.user, class: 'gravatar me-3' %>
      <div>
        <span class="user"><%= link_to activity.user.name, activity.user %></span>
        <span class="activity-meta d-block text-muted">
          <br> <%= activity.run_at.strftime("%B %d, %Y at %I:%M %p") %> </br>
        </span>
      </div>
    </div>
    <h5 class="activity-title mb-3"><%= activity.title %></h5>
    <h6 class "activity-location"><%= activity.location %></h6>
    <div class="activity-stats mb-3 d-flex align-items-center">
      <div class="distance me-3 text-center">
          <% distance = activity.distance %>
          <% formatted_distance = number_with_precision(distance, precision: 2) %>
          
          <% if distance.present? && distance != 0 && distance != distance.to_i %>
            <strong><%= formatted_distance %> km</strong>
          <% else %>
            <strong><%= distance.to_i %> km</strong>
          <% end %>
        <span class="text-muted">Distance</span>
      </div>
      <div class="pace me-3 text-center">
        <strong> 
          <%= number_with_precision((activity.hours * 60 + activity.minutes + activity.seconds / 60.0) / activity.distance, precision: 2) %>/km
        </strong>
        <span class="text-muted">Pace</span>
      </div>
      <div class="duration text-center">
        <strong>
          <% if activity.hours > 0 %>
            <%= activity.hours %>h 
          <% end %>
          <%= activity.minutes %>m 
          <%= activity.seconds %>s
        </strong>
        <span class="text-muted">Duration</span>
      </div>
    </div>
    <p class="activity-description mb-3"><%= activity.description %></p>
    <p class="activity-timestamp text-muted">
      Posted <%= time_ago_in_words(activity.created_at) %> ago.
    </p>
    <% if current_user?(activity.user) || current_user.admin? %>
      <div class="d-flex">
        <%= link_to "Edit", edit_activity_path(activity), class: "btn btn-primary" %>
        <%= button_to "Delete", activity, method: :delete,
                                          data: { confirm: "Are you sure?" }, class: "btn btn-danger me-2" %>
      </div>
    <% end %>
  </div>
</li>

app/views/activities/edit.html.erb
<%# app/views/activities/edit.html.erb %>
<h1>Edit Activity</h1>

<%= render 'shared/activity_form', activity: @activity %>

app/views/activities/new.html.erb
<%= render 'shared/activity_form', activity: @activity %>