config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'add_activity', to: 'static_pages#add_activity', as: 'add_activity'
  resources :users
  resources :activities
  resources :activities do
    collection do
      get :weekly_distances
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>JogTrack | Run & Track</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
            <%= link_to "JogTrack", root_path, id: "logo" %>
            <nav>
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home", root_path %></li>
                    <% if logged_in? %>

                        <li><%= link_to "Add Activity", add_activity_path %></li>
                        <li><%= link_to "Users", users_path %></li>
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li><%= button_to "Log out", logout_path, method: :delete, class: "logout-button" %></li>

                    <% else %>

                        <li><%= link_to "Log in", login_path %></li>
                        
                    <% end %>

                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
    </div>
</body>
</html>